backend:
  name: git-gateway
  branch: main

media_folder: "Blog/{{slug}}/images"
public_folder: "/Blog/{{slug}}/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "Blog"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    format: "frontmatter"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
